/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package GUI;

/**
 *
 * @author Inas
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        gestionCategorieMenuItem = new javax.swing.JMenuItem();
        gestionClientMenuItem = new javax.swing.JMenuItem();
        gestionChambreMenuItem = new javax.swing.JMenuItem();
        gestionReservationMenuItem = new javax.swing.JMenuItem();
        gestionUtilisateurMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        chambreEntreDatesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(102, 255, 255));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        gestionCategorieMenuItem.setMnemonic('o');
        gestionCategorieMenuItem.setText("GestionCategorie");
        gestionCategorieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionCategorieMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(gestionCategorieMenuItem);

        gestionClientMenuItem.setMnemonic('s');
        gestionClientMenuItem.setText("GestionClient");
        gestionClientMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionClientMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(gestionClientMenuItem);

        gestionChambreMenuItem.setMnemonic('a');
        gestionChambreMenuItem.setText("GestionChambre");
        gestionChambreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionChambreMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(gestionChambreMenuItem);

        gestionReservationMenuItem.setText("GestionReservation");
        gestionReservationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionReservationMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(gestionReservationMenuItem);

        gestionUtilisateurMenuItem.setText("GestionUtilisateur");
        gestionUtilisateurMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionUtilisateurMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(gestionUtilisateurMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu2.setText("Recherche");

        chambreEntreDatesMenuItem.setText("RechecheChambreEntreDates");
        chambreEntreDatesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chambreEntreDatesMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(chambreEntreDatesMenuItem);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void gestionCategorieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionCategorieMenuItemActionPerformed
        // TODO add your handling code here:
        CategorieForm c = new CategorieForm();
        desktopPane.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_gestionCategorieMenuItemActionPerformed

    private void gestionClientMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionClientMenuItemActionPerformed
        // TODO add your handling code here:
        ClientForm cl = new ClientForm();
        desktopPane.add(cl);
        cl.setVisible(true);
    }//GEN-LAST:event_gestionClientMenuItemActionPerformed

    private void gestionChambreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionChambreMenuItemActionPerformed
            // TODO add your handling code here:
            ChambreForm ch = new ChambreForm();
            desktopPane.add(ch);
            ch.setVisible(true);
            
    }//GEN-LAST:event_gestionChambreMenuItemActionPerformed

    private void gestionReservationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionReservationMenuItemActionPerformed
        // TODO add your handling code here:
        ReservationForm res = new ReservationForm();
        desktopPane.add(res);
        res.setVisible(true);
    }//GEN-LAST:event_gestionReservationMenuItemActionPerformed

    private void gestionUtilisateurMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUtilisateurMenuItemActionPerformed
        // TODO add your handling code here:
        UtilisateurForm uf = new UtilisateurForm();
        desktopPane.add(uf);
        uf.setVisible(true);
    }//GEN-LAST:event_gestionUtilisateurMenuItemActionPerformed

    private void chambreEntreDatesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chambreEntreDatesMenuItemActionPerformed
        // TODO add your handling code here:
        ChambreEntreDatesForm ced = new ChambreEntreDatesForm();
        desktopPane.add(ced);
        ced.setVisible(true);
    }//GEN-LAST:event_chambreEntreDatesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem chambreEntreDatesMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem gestionCategorieMenuItem;
    private javax.swing.JMenuItem gestionChambreMenuItem;
    private javax.swing.JMenuItem gestionClientMenuItem;
    private javax.swing.JMenuItem gestionReservationMenuItem;
    private javax.swing.JMenuItem gestionUtilisateurMenuItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
